services:
  backend:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./.env:/app/.env
    restart: always

  postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"

    ports:
      - "5432:5432"

    volumes:
      - postgres-data-str:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

volumes:
  postgres-data-str:
    name: postgres-data-str

