services:
  server:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:13

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
    restart: always
    environment:
      DB_USER: postgres
      POSTGRES_PASSWORD: pg_password
      DB_NAME: back_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: